### ISSUE TITLE
Consider storing the accessToken in Secrets API, not plaintext in settings.

### ISSUE THREAD

**Issue by grrowl** [dannymidnight/vscode-buildkite#14]
Since the scope of the graphql token is essentially unlimited, it's a big security vulnerability if this setting is leaked through Settings Sync or other settings-sharing means. Please consider moving it to the Secrets API introduced in vscode 1.53

https://code.visualstudio.com/updates/v1_53#_secrets-api
https://github.com/microsoft/vscode/issues/112249
https://code.visualstudio.com/api/references/vscode-api#SecretStorage :tada:

**Comment by dannymidnight** [comment]
Nice one. That was definitely something that didn't feel quite right when first implementing this so will take a look when I get a chance.

**Comment by mskelton** [comment]
I just opened a PR #16 to fix this issue.
