### ISSUE TITLE
Rate Limiting & Query Complexity

### ISSUE THREAD

**Issue by mitchwd** [dannymidnight/vscode-buildkite#36]
Just a heads up- BuildKite has recently introduced rate limiting for their GraphQL endpoint. After some digging, it turns out this extension was chewing up most of our hourly rate limit, because it was polling every 120 seconds, with a heavy complexity.

More info here: https://buildkite.com/docs/apis/graphql/graphql-resource-limits

**Comment by dannymidnight** [comment]
Hey @mitchwd, thanks for the report and apologies for the slow response on this one.

Just took a look into this one yesterday and I should have a fix rolled out relatively soon – I'll keep you posted.

**Comment by dannymidnight** [comment]
Hey @mitchwd, just following up on this one. I've published a new release that should've fixed the issue. 

Thanks again for reporting and let me know if you're still having any issues.
